### ISSUE TITLE
No connect

### ISSUE THREAD

**Issue by Fungraphic** [Casterlabs/Multistream#1]
I'm on linux.
OBS does not want to connect to "rtmp://localhost:1935"
I checked with the following commands that everything was ok.
sudo lsof -i:1935
netstat -ltn
I don't put a key in obs.
![obs3](https://user-images.githubusercontent.com/26345101/209445520-f49d506f-3f43-437d-a9bf-7e60b4a653b6.png)
![obs1](https://user-images.githubusercontent.com/26345101/209445478-b167c133-c373-46bb-bc4e-fb8fb3f268a2.png)
![obs2](https://user-images.githubusercontent.com/26345101/209445499-de452a7b-12e7-4ffa-bc24-92552cf6c045.png)
![obs](https://user-images.githubusercontent.com/26345101/209445429-59720d56-a672-4a31-a857-dc400dae6914.png)

**Comment by e3ndr** [comment]
Sorry for missing this GitHub never sent me an email, I just fixed this bug in 1.0.2. Give it a try.
