### ISSUE TITLE
Windows - Closing a Console Does not Terminate FFMPEG

### ISSUE THREAD

**Issue by Glitch3dPenguin** [Casterlabs/Multistream#2]
When running on Windows, if you close the console window while running the included bat script FFMPEG will not terminate. It will continue to run in the background and will keep opening every time you launch the BAT file. There is no indication on the Java app that there are other instances of on the same port or IP. It just won't work. 

I have not seen if a CTRL + C will properly close FFMPEG so that might be worth looking into.

**Comment by e3ndr** [comment]
Just fixed this in 1.0.3. While I can't do anything about you pressing the X on cmd (Windows kills the process directly), FFMpeg will automatically time itself out after 30 seconds.
