### ISSUE TITLE
Windows 11 - OBS doesn't connect to Multistream.

### ISSUE THREAD

**Issue by Haihatu** [Casterlabs/Multistream#3]
I think I have everything set up right... but OBS decided not to connect to the multistream server, for some reason.
![image](https://github.com/Casterlabs/Multistream/assets/83486315/dd8255bc-99c9-4517-a8fc-4bd4327035fa)

**Comment by e3ndr** [comment]
You have your terminal paused, are you sure that the program properly loaded?

**Comment by Haihatu** [comment]
yeah, I unpaused it but the program does not properly load. not on this version, and not on any version prior. my friend even sent me his config as a test but it still doesn't work on my computer for some reason.

![image](https://github.com/Casterlabs/Multistream/assets/83486315/529784a4-5df2-415b-8b4a-f83724ee02f2)

**Comment by e3ndr** [comment]
Are you using the windows.zip release or the Jar file directly?

**Comment by Haihatu** [comment]
im using the windows.zip release and also using the start.bat file
